/* Bundles src/assets/svgicons/*.svg into public/sprite.svg and writes the
   matching IconName union, so <Icon name> only accepts icons that exist. */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import SVGSpriter from 'svg-sprite';
import { optimize } from 'svgo';
import svgoConfig from './svgo.config.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const inputDir = path.resolve(__dirname, '../src/assets/svgicons');
const outputDir = path.resolve(__dirname, '../src/assets/sprite');
const publicOutputDir = path.resolve(__dirname, '../public');

if (!fs.existsSync(inputDir)) {
  fs.mkdirSync(inputDir, { recursive: true });
  console.warn(`Created missing input folder: ${inputDir}`);
  console.warn('Add SVG files to generate a sprite.');
  process.exit(0);
}

const svgFiles = fs.readdirSync(inputDir).filter((file) => path.extname(file) === '.svg');

if (svgFiles.length === 0) {
  console.warn('No SVG files found in:', inputDir);
  process.exit(0);
}

const spriter = new SVGSpriter({
  mode: {
    symbol: {
      dest: '.',
      sprite: 'sprite.svg',
    },
  },
  shape: {
    id: {
      generator: (name) => path.basename(name, '.svg'),
    },
  },
  svg: {
    xmlDeclaration: false,
    doctypeDeclaration: false,
    dimensionAttributes: true,
    rootAttributes: {
      viewBox: '0 0 0 0',
    },
  },
});

svgFiles.forEach((file) => {
  const filePath = path.join(inputDir, file);
  const svgRaw = fs.readFileSync(filePath, 'utf-8');

  const { data: optimizedSvg } = optimize(svgRaw, {
    path: filePath,
    ...svgoConfig,
  });

  spriter.add(path.resolve(filePath), file, optimizedSvg);
  console.log(`optimized: ${file}`);
});

spriter.compile((error, result) => {
  if (error) {
    console.error('Sprite generation failed:', error);
    process.exit(1);
  }

  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  // Only the public copy is served; Icon resolves /sprite.svg#name at runtime.
  fs.writeFileSync(path.join(publicOutputDir, 'sprite.svg'), result.symbol.sprite.contents);
  console.log('\nSprite written to public/sprite.svg');

  const iconNames = svgFiles.map((file) => path.basename(file, '.svg'));
  const typeDefinition = `// This file is auto-generated by scripts/generate-sprite.mjs
// Do not edit manually
export type IconName =
${iconNames.map((name) => `  | '${name}'`).join('\n')};
`;

  fs.writeFileSync(path.join(outputDir, 'types.ts'), typeDefinition);
  console.log('Icon names written to src/assets/sprite/types.ts');
});
